### PR TITLE
Support for full PHPUnit public API

### LINKED ISSUE #6: Support for full PHPUnit public API
Related to: [Support for full PHPUnit public API](https://github.com/Codeception/lib-asserts/pull/5)

- [x] Waiting for merge to initiate changes in this repository

### PR DESCRIPTION
**Pull request by ghost**
Closes #6

- [x]  Support for full PHPUnit public API
- [x]  Optimized readability and maintainability of the code
- [x]  Organized the tests of the asserts in alphabetical order and according to their source
- [x]  Updated all docs about asserts

@Naktibalda Can you please take a look here and [there.](https://github.com/Codeception/lib-asserts/pull/5)
It would be great if the changes were merged there to test through the CI here 👍 .

### CODE REVIEW

**Comment by DavertMik** [comment]
Cool, thank you for refactoring this part!
Could you look into failing tests? 

```
Unit Tests (10) --------------------------------------------
PHP Fatal error:  The modifiers of the trait method assertClassHasAttribute() are changed, but this method does not exist. Error in /home/runner/work/module-asserts/module-asserts/src/Codeception/Module/AbstractAsserts.php on line 8
```

Thank you!

**Comment by ghost** [comment]
@DavertMik The tests are failing because Codeception Module Asserts does not support various asserts from [the public phpunit API](https://api.phpunit.de/classes/PHPUnit_Framework_Assert.html), including the one that appears in that error, [I presented a PR](https://github.com/Codeception/lib-asserts/pull/5) to add [a large number of asserts](https://github.com/Codeception/lib-asserts/pull/5/commits/d094eba23eab0cd4dd3f83118e0b0b48f813307d) that are not available so far, and since [this repository uses that library](https://github.com/Codeception/module-asserts/blob/master/composer.json#L19), the CI server will fail until the changes are made merged first [there.](https://github.com/Codeception/lib-asserts/pull/5)

Thank you!

**Review by Naktibalda — CHANGES_REQUESTED** [review]
Composer command in Github Actions fails because it takes too long.
@TavoNiievez Please make this change #8 in your branch.

**Comment by Naktibalda** [comment]
I will fix it myself.

**Pull request merged**
